### ISSUE TITLE
Tutorial on multichannel images

### ISSUE THREAD

**Issue by lext** [Oulu-IMEDS/solt#12]
Example with satellite images

**Comment by aisosalo** [comment]
> Example with satellite images

For example something like reported in [this](https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/IV-2-W7/47/2019/isprs-annals-IV-2-W7-47-2019.pdf) paper (Data Augmentation Approaches for Satellite Image Super-Resolution)?
