### ISSUE TITLE
Requesting additional accepted type 'list' to support reading from yaml-file

### ISSUE THREAD

**Issue by aisosalo** [Oulu-IMEDS/solt#79]
It would good to have `list` as accepted type [here](https://github.com/Oulu-IMEDS/solt/blob/485bfb0d471134f75e09d06aa5e9ce4b57c0e13c/solt/transforms/_transforms.py#L617) to support reading from yaml-file.

**Comment by lext** [comment]
Doesn't it work already if you use `from_yaml`? https://oulu-imeds.github.io/solt/utils.html#solt.utils.from_yaml

**Comment by lext** [comment]
I think I have found the bug. The fixed version is now in master.
