### ISSUE TITLE
3D transforms

### ISSUE THREAD

**Issue by lext** [Oulu-IMEDS/solt#8]
Module 3D transforms would be nice to have. First suggested transforms are crops, flips and rotations 90 degrees

**Comment by soupault** [comment]
Several repos for reference:
- https://github.com/deepmind/multidim-image-augmentation
- https://github.com/ashawkey/volumentations#implemented-augmentations

**Comment by soupault** [comment]
https://github.com/MIC-DKFZ/batchgenerators/

**Comment by soupault** [comment]
https://github.com/PhoenixDL/rising
https://github.com/fepegar/torchio
